//Next JS imports
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";

//Dependencies imports
import { useEffect, useState } from "react";
import { GoogleFonts } from "next-google-fonts";

//Assets import
import DiceIllustration from "../public/dice-illustration.svg";

//Redux import
import { useSelector, useDispatch } from "react-redux";
import { setCurrentUser } from "../redux/general/general.actions";

//Near imports
import { signIn, signOut, viewFunction } from "../near/near-setup";

export default function Home() {
  const currentUser = useSelector((state) => state.general.currentUser);
  const dispatch = useDispatch();
  const router = useRouter();

  useEffect(() => {
    const redirect = localStorage.getItem("redirect");

    if (currentUser && redirect) {
      localStorage.removeItem("redirect");
      router.push("/dashboard");
    }
  }, currentUser);

  return (
    <div className="w-screen h-screen">
      <GoogleFonts href="https://fonts.googleapis.com/css2?family=Manrope:wght@300;400;500;700&display=swap" />
      <Head>
        <title>Near Dice Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="w-full px-14 py-4 flex justify-between items-center">
        <div></div>
        <h1 className="font-bold ml-20 text-3xl">Near Dice Game</h1>
        <div
          onClick={() => {
            if (currentUser) {
              router.push("/dashboard");
            } else {
              localStorage.setItem("redirect", true);
              signIn();
            }
          }}
          className=" order-2 border-2 border-black text-black p-1 rounded-xl font-bold cursor-pointer transition-all duration-500  hover:bg-black hover:text-white"
        >
          <span>Get Started</span>
        </div>
      </nav>
      <div className="flex justify-center w-full -mb-32">
        <Image src={DiceIllustration} alt="dice-illustration" width={220} />
      </div>

      <section className="h-4/6 w-full flex flex-col justify-center items-center px-14">
        <span className="font-bold text-xl mb-8">How To Play</span>
        <div className="w-full flex justify-between items-center">
          <div className="flex flex-col gap-y-2 justify-center w-5/12">
            <span className="text-center font-semibold text-lg">Creator</span>
            <p className="text-center font-medium">
              Create a game with setting an initial bet.Share the room id with
              friends, or wait for people to join your room.
              <br />
              Winner takes it all.
            </p>
          </div>
          <div className="flex flex-col gap-y-2 justify-center w-1/2">
            <span className="text-center text-lg font-semibold">Player</span>
            <p className="text-center font-medium">
              Join any available room, or create your own. Try to guess the
              correct dice number to win.
              <br />
              May the odds be in your favor
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}
